/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.montpellier.ReciboImposto.View;

import br.com.montpellier.ReciboImposto.Controller.ControllerCliente;
import br.com.montpellier.ReciboImposto.Model.ModelCliente;
import br.com.montpellier.ReciboImposto.Singleton.GerenciadorDeTelas;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author santos
 */
public class ViewCliente extends javax.swing.JFrame {

    /**
     * Creates new form telaUsuario
     */
    public ViewCliente() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jtClientes.getModel();
        jtClientes.setRowSorter(new TableRowSorter(modelo));
        readJTable();
    }

    public void readJTable() {

        DefaultTableModel modelo = (DefaultTableModel) jtClientes.getModel();
        modelo.setNumRows(0);
        jtClientes.getColumnModel().getColumn(0).setPreferredWidth(10);
        jtClientes.getColumnModel().getColumn(1).setPreferredWidth(80);
        jtClientes.getColumnModel().getColumn(2).setPreferredWidth(80);
        jtClientes.getColumnModel().getColumn(3).setPreferredWidth(80);
        jtClientes.getColumnModel().getColumn(4).setPreferredWidth(30);
        jtClientes.getColumnModel().getColumn(5).setPreferredWidth(8);
        jtClientes.getColumnModel().getColumn(6).setPreferredWidth(50);
        jtClientes.getColumnModel().getColumn(7).setPreferredWidth(80);
        ControllerCliente clientContr = new ControllerCliente();

        DefaultTableCellRenderer tabela = new DefaultTableCellRenderer();
        tabela.setHorizontalAlignment(SwingConstants.LEFT);
        jtClientes.getColumnModel().getColumn(0).setCellRenderer(tabela);

        for (ModelCliente client : clientContr.read()) {

            modelo.addRow(new Object[]{
                client.getCodigo(),
                client.getNome(),
                client.getCpf(),
                client.getCnpj(),
                client.getCidade(),
                client.getEstado(),
                client.getTelefone(),
                client.getEmail(),});

        }
    }

    public void readJTableBusca(String nome) {

        DefaultTableModel modelo = (DefaultTableModel) jtClientes.getModel();
        modelo.setNumRows(0);
        jtClientes.getColumnModel().getColumn(0).setPreferredWidth(10);
        jtClientes.getColumnModel().getColumn(1).setPreferredWidth(80);
        jtClientes.getColumnModel().getColumn(2).setPreferredWidth(80);
        jtClientes.getColumnModel().getColumn(3).setPreferredWidth(80);
        jtClientes.getColumnModel().getColumn(4).setPreferredWidth(30);
        jtClientes.getColumnModel().getColumn(5).setPreferredWidth(8);
        jtClientes.getColumnModel().getColumn(6).setPreferredWidth(50);
        jtClientes.getColumnModel().getColumn(7).setPreferredWidth(80);
        ControllerCliente clientContr = new ControllerCliente();

        DefaultTableCellRenderer tabela = new DefaultTableCellRenderer();
        tabela.setHorizontalAlignment(SwingConstants.LEFT);
        jtClientes.getColumnModel().getColumn(0).setCellRenderer(tabela);

        for (ModelCliente client : clientContr.readForNome(nome)) {

            modelo.addRow(new Object[]{
                client.getCodigo(),
                client.getNome(),
                client.getCpf(),
                client.getCnpj(),
                client.getCidade(),
                client.getEstado(),
                client.getTelefone(),
                client.getEmail(),});

        }
    }

    public void readJTableQuery(String cliente) {

        DefaultTableModel modelo = (DefaultTableModel) jtClientes.getModel();
        modelo.setNumRows(0);
        ControllerCliente clientContr = new ControllerCliente();

        DefaultTableCellRenderer tabela = new DefaultTableCellRenderer();
        tabela.setHorizontalAlignment(SwingConstants.LEFT);
        jtClientes.getColumnModel().getColumn(0).setCellRenderer(tabela);

        for (ModelCliente client : clientContr.readQuery(cliente)) {

            modelo.addRow(new Object[]{
                client.getCodigo(),
                client.getNome(),
                client.getCpf(),
                client.getCnpj(),
                client.getCidade(),
                client.getEstado(),});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        lblLogin = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lblUsuarios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtClientes = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Clientes");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnSair.setBackground(new java.awt.Color(235, 249, 60));
        btnSair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSair.setText("Fechar");
        btnSair.setToolTipText("Fechar");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSairMouseExited(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblLogin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblLogin.setText("Nome");

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        btnNovo.setBackground(new java.awt.Color(235, 249, 60));
        btnNovo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/montpellier/ReciboImposto/Imagens/novo.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setToolTipText("Cadastrar um novo usuário");
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNovoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNovoMouseExited(evt);
            }
        });
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(235, 249, 60));
        btnExcluir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/montpellier/ReciboImposto/Imagens/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Selecione um usuário para excluir");
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExcluirMouseExited(evt);
            }
        });
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(235, 249, 60));
        btnLimpar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/montpellier/ReciboImposto/Imagens/limpar10px.png"))); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.setToolTipText("Limpar filtro");
        btnLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimparMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimparMouseExited(evt);
            }
        });
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblUsuarios.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblUsuarios.setText("Clientes");

        jtClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "CPF", "CNPJ", "Cidade", "Estado", "Telefone", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jtClientes.getTableHeader().setReorderingAllowed(false);
        jtClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtClientesMouseClicked(evt);
            }
        });
        jtClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtClientesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtClientes);
        if (jtClientes.getColumnModel().getColumnCount() > 0) {
            jtClientes.getColumnModel().getColumn(0).setResizable(false);
            jtClientes.getColumnModel().getColumn(1).setResizable(false);
            jtClientes.getColumnModel().getColumn(2).setResizable(false);
            jtClientes.getColumnModel().getColumn(3).setResizable(false);
            jtClientes.getColumnModel().getColumn(4).setResizable(false);
            jtClientes.getColumnModel().getColumn(5).setResizable(false);
            jtClientes.getColumnModel().getColumn(6).setResizable(false);
            jtClientes.getColumnModel().getColumn(7).setResizable(false);
        }

        btnEditar.setBackground(new java.awt.Color(235, 249, 60));
        btnEditar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/montpellier/ReciboImposto/Imagens/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Selecione um usuário para editar");
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLimpar)
                                    .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(btnNovo)
                                .addGap(94, 94, 94)
                                .addComponent(btnExcluir)
                                .addGap(94, 94, 94)
                                .addComponent(btnEditar)))
                        .addGap(0, 211, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSair)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(432, 432, 432))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuarios)
                .addGap(31, 31, 31)
                .addComponent(lblLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnLimpar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnNovo))
                .addGap(24, 24, 24)
                .addComponent(btnSair)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
       this.dispose();
       GerenciadorDeTelas.getInstanse().getViewPricipal().setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        this.dispose();

        GerenciadorDeTelas.getInstanse().getViewCadastroCliente().setVisible(true);


    }//GEN-LAST:event_btnNovoActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed

        // System.out.println(controller.testaLogin(tfLogin.getText()));
        //  System.out.println(tfLogin.getText());
        if (tfNome.getText().isEmpty() != true) {

            readJTableBusca(tfNome.getText());

        } else {
            JOptionPane.showMessageDialog(rootPane, "Cliente não encontrado!", "Erro!", JOptionPane.ERROR_MESSAGE);
            tfNome.setText("");
            readJTable();
        }

    }//GEN-LAST:event_tfNomeActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        tfNome.setText("");
        readJTable();


    }//GEN-LAST:event_btnLimparActionPerformed

    ModelCliente clientModel = new ModelCliente();
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (jtClientes.getSelectedRow() != -1) {
            this.dispose();
            GerenciadorDeTelas.getInstanse().getViewEditarCliente().setVisible(true);
            GerenciadorDeTelas.getInstanse().getViewEditarCliente().preencheUsuario(clientModel);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Cliente", "Erro!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void jtClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtClientesMouseClicked

        clientModel.setCodigo(0);
        clientModel.setNome("");
        clientModel.setCpf("");
        clientModel.setCnpj("");
        clientModel.setCidade("");
        clientModel.setEstado("");
        if (jtClientes.getSelectedRow() != -1) {
//            clientModel.setCodigo(Integer.parseInt(jtClientes.getValueAt(jtClientes.getSelectedRow(), 0).toString()));
//            clientModel.setNome(jtClientes.getValueAt(jtClientes.getSelectedRow(), 1).toString());
//            clientModel.setCpf(jtClientes.getValueAt(jtClientes.getSelectedRow(), 2).toString());
//            clientModel.setCnpj(jtClientes.getValueAt(jtClientes.getSelectedRow(), 3).toString());
//            clientModel.setCidade(jtClientes.getValueAt(jtClientes.getSelectedRow(), 4).toString());
//            clientModel.setEstado(jtClientes.getValueAt(jtClientes.getSelectedRow(), 5).toString());
//            clientModel.setRua(jtClientes.getValueAt(jtClientes.getSelectedRow(), 6).toString());
//            clientModel.setBairro(jtClientes.getValueAt(jtClientes.getSelectedRow(), 7).toString());

              ControllerCliente clientControl = new ControllerCliente();
             String indice = jtClientes.getValueAt(jtClientes.getSelectedRow(), 0).toString();
             clientModel.setCodigo(clientControl.queryClientePorCodigo(indice).getCodigo());
             clientModel.setNome(clientControl.queryClientePorCodigo(indice).getNome());
             clientModel.setCpf(clientControl.queryClientePorCodigo(indice).getCpf());
             clientModel.setCnpj(clientControl.queryClientePorCodigo(indice).getCnpj());
             clientModel.setCidade(clientControl.queryClientePorCodigo(indice).getCidade());
             clientModel.setEstado(clientControl.queryClientePorCodigo(indice).getEstado());
             clientModel.setRua(clientControl.queryClientePorCodigo(indice).getRua());
             clientModel.setBairro(clientControl.queryClientePorCodigo(indice).getBairro());
             clientModel.setTelefone(clientControl.queryClientePorCodigo(indice).getTelefone());
             clientModel.setEmail(clientControl.queryClientePorCodigo(indice).getEmail());
        }
    }//GEN-LAST:event_jtClientesMouseClicked

    private void jtClientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtClientesKeyReleased

        clientModel.setCodigo(0);
        clientModel.setNome("");
        clientModel.setCpf("");
        clientModel.setCnpj("");
        clientModel.setCidade("");
        clientModel.setEstado("");

        if (jtClientes.getSelectedRow() != -1) {

//            //DefaultTableModel modelo = (DefaultTableModel) jtClientes.getModel();
//            // DefaultTableModel modelo = (DefaultTableModel) jtClientes.getModel();
//            clientModel.setCodigo(Integer.parseInt(jtClientes.getValueAt(jtClientes.getSelectedRow(), 0).toString()));
//            //System.out.println(jtClientes.getValueAt(jtClientes.getSelectedRow(), 0).toString());
//            clientModel.setNome(jtClientes.getValueAt(jtClientes.getSelectedRow(), 1).toString());
//            //System.out.println(jtClientes.getValueAt(jtClientes.getSelectedRow(), 0).toString());
//            clientModel.setCpf(jtClientes.getValueAt(jtClientes.getSelectedRow(), 2).toString());
//            // System.out.println(jtClientes.getValueAt(jtClientes.getSelectedRow(), 1).toString());
//            clientModel.setCnpj(jtClientes.getValueAt(jtClientes.getSelectedRow(), 3).toString());
//            // System.out.println(jtClientes.getValueAt(jtClientes.getSelectedRow(), 2).toString());
//            clientModel.setCidade(jtClientes.getValueAt(jtClientes.getSelectedRow(), 4).toString());
//            clientModel.setEstado(jtClientes.getValueAt(jtClientes.getSelectedRow(), 5).toString());
              
              ControllerCliente clientControl = new ControllerCliente();
             String indice = jtClientes.getValueAt(jtClientes.getSelectedRow(), 0).toString();
             clientModel.setCodigo(clientControl.queryClientePorCodigo(indice).getCodigo());
             clientModel.setNome(clientControl.queryClientePorCodigo(indice).getNome());
             clientModel.setCpf(clientControl.queryClientePorCodigo(indice).getCpf());
             clientModel.setCnpj(clientControl.queryClientePorCodigo(indice).getCnpj());
             clientModel.setCidade(clientControl.queryClientePorCodigo(indice).getCidade());
             clientModel.setEstado(clientControl.queryClientePorCodigo(indice).getEstado());
             clientModel.setRua(clientControl.queryClientePorCodigo(indice).getRua());
             clientModel.setBairro(clientControl.queryClientePorCodigo(indice).getBairro());
             clientModel.setTelefone(clientControl.queryClientePorCodigo(indice).getTelefone());
             clientModel.setEmail(clientControl.queryClientePorCodigo(indice).getEmail());  


        }
    }//GEN-LAST:event_jtClientesKeyReleased

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (jtClientes.getSelectedRow() != -1) {
            System.out.println("ID: " + jtClientes.getValueAt(jtClientes.getSelectedRow(), 0) + "Nome: " + jtClientes.getValueAt(jtClientes.getSelectedRow(), 1));
            int op = JOptionPane.showConfirmDialog(this, "Deseja Mesmo Excluir o Usuário de ID = " + jtClientes.getValueAt(jtClientes.getSelectedRow(), 0)
                    + " " + "Nome: " + jtClientes.getValueAt(jtClientes.getSelectedRow(), 1), "Aviso do Sistema", JOptionPane.YES_NO_OPTION);
            if (op == JOptionPane.YES_OPTION) {
                ModelCliente u = new ModelCliente();
                ControllerCliente controller = new ControllerCliente();

                u.setCodigo((int) jtClientes.getValueAt(jtClientes.getSelectedRow(), 0));

                controller.delete(u);

                // txtDesc.setText("");
                // txtQtd.setText("");
                // txtPreco.setText("");
                readJTable();

            }
            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente para excluir.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLimparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseEntered
        btnLimpar.setBackground(new Color(235, 214, 0));
        btnLimpar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnLimparMouseEntered

    private void btnLimparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseExited
        btnLimpar.setBackground(new Color(235, 249, 60));
        btnLimpar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnLimparMouseExited

    private void btnNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseEntered
        btnNovo.setBackground(new Color(235, 214, 0));
        btnNovo.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnNovoMouseEntered

    private void btnNovoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseExited
        btnNovo.setBackground(new Color(235, 249, 60));
        btnNovo.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnNovoMouseExited

    private void btnExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseEntered
        btnExcluir.setBackground(new Color(235, 214, 0));
        btnExcluir.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnExcluirMouseEntered

    private void btnExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseExited
        btnExcluir.setBackground(new Color(235, 249, 60));
        btnExcluir.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnExcluirMouseExited

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        btnEditar.setBackground(new Color(235, 214, 0));
        btnEditar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        btnEditar.setBackground(new Color(235, 249, 60));
        btnEditar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseEntered
        btnSair.setBackground(new Color(235, 214, 0));
        btnSair.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnSairMouseEntered

    private void btnSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseExited
        btnSair.setBackground(new Color(235, 249, 60));
        btnSair.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnSairMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtClientes;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
